---
title: "CORONA Dashboard v1.0"
output: 
  flexdashboard::flex_dashboard:
    theme: yeti
    orientation: rows
    vertical_layout: fill
---
<style>                     
.navbar {
  background-color:DarkBlue;
  border-color:black;
}
.navbar-brand {
color:white!important;
}
</style> 

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(RColorBrewer)
library(ggmap)
library(maps)
library(rgdal)
library(scales)
library(maptools)
library(gridExtra)
library(rgeos)
library(mapproj)
library(dplyr)

ci<-read.csv("My_covid_data.csv")

ci$confirmed<-as.numeric(ci$confirmed)
ci$cured<-as.numeric(ci$cured)
ci$death<-as.numeric(ci$death)

conf <- sum(ci[,3])
cur <-sum(ci[,4])
dt <-sum(ci[,5])

covidind<-read.csv("My_covid_data.csv")
covidind$confirmed<-as.numeric(covidind$confirmed)
covidind$cured<-as.numeric(covidind$cured)
covidind$death<-as.numeric(covidind$death)

states_shape = readShapeSpatial("IND_adm1.shp")
class(states_shape)
names(states_shape)
print(states_shape$ID_1)
print(states_shape$NAME_1)
plot(states_shape)

score <- covidind$cured
State_data = data.frame(id=states_shape$ID_1, NAME_1=states_shape$NAME_1, score)

fortify_shape = fortify(states_shape, region = "ID_1")
Merged_data = merge(fortify_shape, State_data, by="id", all.x=TRUE)
Map_plot = Merged_data[order(Merged_data$order), ]

addUnits <- function(n) {
  labels <- ifelse(n < 1000, n,  # less than thousands
                   ifelse(n < 1e6, paste0(round(n/1e3), 'k'),  # in thousands
                          ifelse(n < 1e9, paste0(round(n/1e6), 'M'),  # in millions
                                 ifelse(n < 1e12, paste0(round(n/1e9), 'B'), # in billions
                                        ifelse(n < 1e15, paste0(round(n/1e12), 'T'), # in trillions
                                               'too big!'
                                        )))))
  return(labels)
}
```


## Column {data-width=150}

### CONFIRMED CASES

```{r}
valueBox(conf)
```

### CURED CASES

```{r}
valueBox(cur)
```

### ACTIVE CASES

```{r}
valueBox(conf-cur-dt)
```

### DEATH CASES

```{r}
valueBox(dt)
```

Row {.tabset .tabset-fade}
-------------------------------------

### CURED STATES

```{r}
ggplot() +
  geom_polygon(data = Map_plot,
               aes(x = long, y = lat, group = group, fill = score),
               color = "black", size = 0.5) +  coord_map() + expand_limits(fill = c(0, NA)) +
  scale_fill_continuous(labels = addUnits)
```


### CONFIRMED CASES

```{r}
ggplot(data = ci, aes(x = states, y = confirmed)) +
  geom_bar(stat = "identity", fill = "blue")+
  coord_flip()+
    labs(x = "States",
       y = "Confirmed",
       title = "Comparing Confirmed cases") +expand_limits(x = c(0, NA), y = c(0, NA)) +
  scale_y_continuous(labels = addUnits) 
```

### DEATH CASES

```{r}
ggplot(data = ci, aes(x = states, y = death)) +
  geom_bar(stat = "identity", fill = "red")+coord_flip()+
  labs(x = "States",
       y = "Death",
       title = "Comparing Death cases") +expand_limits(x = c(0, NA), y = c(0, NA)) +
  scale_y_continuous(labels = addUnits) 
```